Comment class branch
MaayanMordehai/CollegeWebProject pull request #10
Opened 2021-05-03 18:20 UTC by barBen

2021-05-03 18:40 UTC, origranot commented on DGN/Models/Comment.cs
> +        [StringLenght(20), MinimumLenght = 5]
String LENGHHHTTT

2021-05-03 18:50 UTC, bsuro10 requested changes

2021-05-03 18:50 UTC, bsuro10 commented on DGN/Models/Comment.cs
> +        public string Title { get; set; }
We don't need title property

2021-05-03 18:50 UTC, bsuro10 commented on DGN/Models/Comment.cs
> +        [StringLenght(200), MinimumLenght = 5]
StringLength*

2021-05-03 18:50 UTC, bsuro10 commented on DGN/Models/Comment.cs
> +        public User CommentWriter { get; set; }
[Required]
[ForeignKey("User")]
public int AuthorId { get; set; }

[Required]
public User Author { get; set; }

2021-05-03 18:50 UTC, bsuro10 commented on DGN/Models/Comment.cs
> +        public Article RelatedArticle { get; set; }
[Required]
[ForeignKey("Article")]
public int ArticleId { get; set; }

[Required]
public Article Article { get; set; }

2021-05-09 17:30 UTC, MaayanMordehai approved these changes

2021-05-23 18:05 UTC, MaayanMordehai approved these changes

2021-05-23 18:28 UTC, MaayanMordehai submitted a review, later dismissed

2021-05-23 18:28 UTC, bsuro10 requested changes

2021-05-23 18:28 UTC, bsuro10 commented on DGN/Models/Comment.cs
> +        public string Body { get; set; }
Need to add `[DataType(DataType.MultilineText)]` and `[Required]`

2021-05-23 18:44 UTC, bsuro10 approved these changes

2021-05-23 18:45 UTC, origranot approved these changes

2021-05-23 18:45 UTC, merged