Comments manager
MaayanMordehai/CollegeWebProject pull request #102
Opened 2021-07-26 20:26 UTC by bsuro10

- Added Comments Index for Admin (with permissions) - _/Comments_
- Added 3 params search for comments
- Changed the template of a comment so make sure to check me in comments section of an article, and Comments Index for Admin

#96

2021-07-28 16:55 UTC, MaayanMordehai commented
I think there should be also in which article the comment is, in the manage comment page.

2021-07-28 18:40 UTC, MaayanMordehai commented on DGN/Controllers/CommentsController.cs
> +        public async Task<IActionResult> Search(string body, string fullname, string username)
This should be with [Autorized]
in other functions we won't let anyone unautorized to see comments, so we should not let here.

2021-07-28 18:42 UTC, MaayanMordehai requested changes
Very good!
I'm not sure why it didn't let me do request changes above, so doing it now

2021-07-28 19:10 UTC, bsuro10 commented
> I think there should be also in which article the comment is, in the manage comment page.
> And also do we need details view?

Done.
We don't need details since there are not alot of details so I put everything on the table.

2021-07-28 19:42 UTC, MaayanMordehai approved these changes, later dismissed
Great!!

2021-07-29 05:42 UTC, barBen submitted a review, later dismissed

2021-07-29 16:58 UTC, barBen approved these changes

2021-07-29 19:02 UTC, origranot approved these changes

2021-07-29 19:11 UTC, merged