Css html requirements
MaayanMordehai/CollegeWebProject pull request #109
Opened 2021-07-28 18:33 UTC by bsuro10

#94

2021-07-28 19:56 UTC, MaayanMordehai requested changes
Looking Amazing!!!!!!!!!!

2021-07-28 19:56 UTC, MaayanMordehai commented on DGN/Views/Articles/Index.cshtml
> +    <video controls>
add autoplay, it is cooler
"video controles autoplay"

2021-07-28 20:07 UTC, MaayanMordehai approved these changes

2021-07-29 05:39 UTC, barBen approved these changes

2021-07-29 05:39 UTC, merged