User class branch
MaayanMordehai/CollegeWebProject pull request #11
Opened 2021-05-03 18:20 UTC by barBen

2021-05-03 21:04 UTC, MaayanMordehai requested changes
The User should have one to one constrain with the Password :)

2021-05-03 21:17 UTC, MaayanMordehai commented on DGN/Models/User.cs
> +        public string Password { get; set; }
The User should have one to one constrain with the Password :)

2021-05-03 21:19 UTC, MaayanMordehai requested changes

2021-05-03 21:19 UTC, MaayanMordehai commented on DGN/Models/User.cs
> +        public string Password { get; set; }
The User should have one to one constrain with the Password :)

2021-05-21 16:52 UTC, MaayanMordehai requested changes

2021-05-21 16:52 UTC, MaayanMordehai commented on DGN/Models/User.cs
> +        public int PssswordID { get; set; }
need to be:
[ForeignKey("Password")]
public int PasswordId { get; set; }

2021-05-23 17:45 UTC, bsuro10 requested changes

2021-05-23 17:45 UTC, bsuro10 commented on DGN/Models/User.cs
> +        public string Password { get; set; }
Should be from class "Password"

2021-05-23 17:45 UTC, bsuro10 commented on DGN/Models/User.cs
> +        [RegularExpression(@"^[A-Z]+[a-z].*$")]
We don't regular expression, 
we just need to set up minimum characters

2021-05-23 17:45 UTC, bsuro10 commented on DGN/Models/User.cs
> +        [DisplayName("The articles that the user liked")]
We don't need it because it won't be on the form

2021-05-23 17:45 UTC, bsuro10 commented on DGN/Models/User.cs
> +        [DisplayName("Articles The User Wrote")]
We don't need it because it won't be on the form

2021-05-23 18:04 UTC, MaayanMordehai submitted a review, later dismissed

2021-05-23 18:05 UTC, origranot approved these changes, later dismissed
Good job!

2021-05-23 18:09 UTC, bsuro10 requested changes

2021-05-23 18:09 UTC, bsuro10 commented on DGN/Models/User.cs
> +        public IList<ArticleLikes> ArticleLikes { get; set; }
The IList need to be from kind `Article`

2021-05-23 18:19 UTC, origranot approved these changes, later dismissed
Good job!

2021-05-23 18:23 UTC, bsuro10 requested changes

2021-05-23 18:23 UTC, bsuro10 commented on DGN/Models/User.cs
> +        public int PasswordID { get; set; }
Just to make sure write it like this: `PasswordId`

2021-05-23 18:25 UTC, bsuro10 requested changes

2021-05-23 18:25 UTC, bsuro10 commented on DGN/Models/User.cs
> +        public string UserName { get; set; }
You can change to `Username` and then remove [DisplayName("Username")]

2021-05-23 18:26 UTC, MaayanMordehai submitted a review, later dismissed

2021-05-23 18:59 UTC, bsuro10 approved these changes

2021-05-23 19:00 UTC, MaayanMordehai approved these changes

2021-05-23 19:00 UTC, merged