Added like and share button
MaayanMordehai/CollegeWebProject pull request #119
Opened 2021-07-29 18:56 UTC by origranot

#81

2021-07-29 19:11 UTC, bsuro10 submitted a review, later dismissed

2021-07-29 21:06 UTC, MaayanMordehai requested changes
- [ ] Please add seeing how many likes are there :)
- [X] Also the Like button really nice - Loved the Animation. But users won't know if they liked it or not by seeing Like in blue, after user pressed liked turn it to unlike if possible.
@bsuro10

2021-07-29 22:10 UTC, bsuro10 submitted a review, later dismissed
As Maayan said, we need to add `how many users liked the article`

2021-07-29 22:17 UTC, bsuro10 commented
Just need to add the amount of likes

2021-07-31 16:39 UTC, bsuro10 approved these changes

2021-07-31 19:27 UTC, MaayanMordehai approved these changes

2021-07-31 19:28 UTC, merged