Users search
MaayanMordehai/CollegeWebProject pull request #133
Opened 2021-07-31 12:50 UTC by barBen

2021-07-31 13:39 UTC, bsuro10 submitted a review, later dismissed

2021-07-31 14:07 UTC, MaayanMordehai requested changes

2021-07-31 14:07 UTC, MaayanMordehai commented on DGN/Views/Users/Index.cshtml
> +                <a href="Users/Delete/{id}">Delete</a>
There are some changes from main - not every user will have DELETE in the options, look at this page in main and change it to like it's there.

2021-07-31 16:42 UTC, bsuro10 approved these changes

2021-08-01 00:28 UTC, MaayanMordehai approved these changes

2021-08-01 00:28 UTC, merged