Article class branch
MaayanMordehai/CollegeWebProject pull request #14
Opened 2021-05-03 18:36 UTC by bsuro10

#3

2021-05-03 21:23 UTC, MaayanMordehai requested changes

2021-05-03 21:23 UTC, MaayanMordehai commented on DGN/Models/Article.cs
> +using System.Threading.Tasks;
You should remove unneeded 'using'

2021-05-23 17:52 UTC, MaayanMordehai approved these changes, later dismissed

2021-05-23 18:01 UTC, barBen approved these changes

2021-05-23 18:02 UTC, MaayanMordehai approved these changes

2021-05-23 18:05 UTC, merged