Add login and register views.
MaayanMordehai/CollegeWebProject pull request #42
Opened 2021-06-12 12:09 UTC by barBen

2021-06-13 15:31 UTC, origranot approved these changes, later dismissed
Good job!

2021-06-13 19:08 UTC, MaayanMordehai requested changes

2021-06-13 19:08 UTC, MaayanMordehai commented on DGN/Views/Users/Register.cshtml
> +                            <label asp-for="Role" class="control-label"></label>
you should remove the role, the user controller will do default - Client

2021-06-15 17:25 UTC, MaayanMordehai submitted a review, later dismissed

2021-06-19 10:53 UTC, bsuro10 submitted a review, later dismissed

2021-06-19 10:53 UTC, bsuro10 commented on DGN/Views/Shared/_Layout.cshtml
> +                            <a href="/Users/Register" class="nav-btn register-btn">Register</a>
<a asp-controller="Users" asp-action="Register"></a>

2021-06-19 10:53 UTC, bsuro10 commented on DGN/Views/Shared/_Layout.cshtml
> +                            <a href="/Users/Register" class="nav-btn register-btn">Register</a>
Change a tag to include asp-controller and asp-action

2021-06-19 11:00 UTC, bsuro10 approved these changes

2021-06-19 11:01 UTC, MaayanMordehai approved these changes

2021-06-19 11:01 UTC, merged