Contact us search
MaayanMordehai/CollegeWebProject pull request #53
Opened 2021-06-19 10:27 UTC by barBen

2021-06-19 11:02 UTC, bsuro10 approved these changes, later dismissed

2021-07-10 12:32 UTC, origranot requested changes
Change title name, not Index.

2021-07-17 11:10 UTC, bsuro10 requested changes
Search is great!
If you add a branch without Activity Hours it displays "null", change it to something else like "Currently there are no activity hours for this branch"
![Bug2](https://user-images.githubusercontent.com/36992518/126035033-a295ddce-ab8b-4ccf-a5b2-eb7b616f277c.png)

2021-07-17 13:25 UTC, bsuro10 approved these changes
Lit

2021-07-23 11:20 UTC, MaayanMordehai approved these changes, later dismissed

2021-07-23 12:51 UTC, bsuro10 approved these changes, later dismissed

2021-07-23 13:06 UTC, bsuro10 approved these changes

2021-07-23 13:19 UTC, origranot approved these changes

2021-07-23 13:19 UTC, merged