Edit change password view page
MaayanMordehai/CollegeWebProject pull request #54
Opened 2021-06-19 11:28 UTC by barBen

2021-06-19 17:08 UTC, bsuro10 requested changes
Password is plain text - need to be changed to dots
The functionality is not working - should it work?

There is no validation for the password on the client side.
We need 3 validations:
1. Current password match 
2. Password validation (One capital letter, one number, etc.. Like the regex)
3. Password and Confirm password match

2021-07-10 10:52 UTC, MaayanMordehai submitted a review, later dismissed

2021-07-10 12:31 UTC, origranot approved these changes, later dismissed
Good job!

2021-07-11 19:10 UTC, MaayanMordehai submitted a review, later dismissed

2021-07-17 11:04 UTC, bsuro10 requested changes
The submit button should be disabled when you load the page - for example, if I don't write anything I can submit empty fields:
![Bug1](https://user-images.githubusercontent.com/36992518/126034916-9b9ab38a-13af-4eb3-8251-709195800723.png)

2021-07-17 12:37 UTC, bsuro10 approved these changes

2021-07-23 11:17 UTC, MaayanMordehai approved these changes

2021-07-23 12:35 UTC, merged