Users view
MaayanMordehai/CollegeWebProject pull request #61
Opened 2021-06-19 14:46 UTC by barBen

#37

2021-06-19 17:12 UTC, bsuro10 requested changes
When you want to delete a user,
the password is plain text and not type=password

After deleting, return to the list of users

2021-07-10 12:30 UTC, origranot approved these changes, later dismissed
Good job!

2021-07-10 12:30 UTC, MaayanMordehai approved these changes, later dismissed

2021-07-12 21:11 UTC, MaayanMordehai requested changes

2021-07-12 21:11 UTC, ghost commented on DGN/Views/Users/Edit.cshtml
>      ViewData["Title"] = "Edit Profile";
There should not be Edit for normal edit, only for edit as admin.
Edit for the user itself is done from the profile, this file should be deleted.

2021-07-12 21:11 UTC, ghost commented on DGN/Views/Users/EditAsAdmin.cshtml
like you did to the register to test the data before sending it to the the server this needs to be on the edit as admin too. (its just the first name, last name to start with capital letter and the email). correct me if i'm wrong @bsuro10

2021-07-13 04:31 UTC, barBen commented on DGN/Views/Users/EditAsAdmin.cshtml
Maybe I did not understand, but if one of them is not as required (First name with capital letter, etc..) you get an error and cant submit the form..

2021-07-13 17:23 UTC, MaayanMordehai approved these changes

2021-07-14 10:49 UTC, origranot approved these changes

2021-07-17 10:54 UTC, bsuro10 requested changes
- When editing a user, his role change to Client (Even if he was admin or author)
- The error message on First Name is not good: (Need to change in Modal)
![Bug0](https://user-images.githubusercontent.com/36992518/126034532-17e0a43e-345f-4129-a260-4b951c4e3282.png)
- When you delete a user - return to the list of users
- You disabled the "Register" button if the user didn't fill the required fields, but you need to add something to tell him what is required and what is not, add a red '*' next to each required field

2021-07-23 12:50 UTC, bsuro10 approved these changes

2021-07-23 12:51 UTC, merged