Create and Edit an article modified css and validation
MaayanMordehai/CollegeWebProject pull request #92
Opened 2021-07-23 15:45 UTC by bsuro10

#82

2021-07-24 22:18 UTC, MaayanMordehai requested changes

2021-07-24 22:18 UTC, MaayanMordehai commented on DGN/Views/Articles/Create.cshtml
> +                            <input type="file" name="ImageFile" id="ImageFile" class="form-control-file">
replace with this to accept only images. 
input type="file" name="ImageFile" id="ImageFile" class="form-control-file" accept="image/x-png,image/jpg,image/jpeg"

2021-07-24 22:18 UTC, MaayanMordehai commented on DGN/Views/Articles/Edit.cshtml
> +                            <input type="file" name="ImageFile" id="ImageFile" class="form-control-file">
replace with this to accept only images.
input type="file" name="ImageFile" id="ImageFile" class="form-control-file" accept="image/x-png,image/jpg,image/jpeg"

2021-07-25 20:18 UTC, origranot approved these changes

2021-07-25 20:29 UTC, MaayanMordehai approved these changes

2021-07-25 20:29 UTC, merged